version: "3"

services:
  dlna-server:
    build: .
    volumes:
      - /data:/opt
    ports:
      - "8200:8200/udp"
      - "8200:8200/tcp"
    networks:
      static:
        ipv4_address: 10.5.0.5
      
networks:
  static:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1